name: Run Python Script

on:
  schedule:
    - cron: '*/15 * * * *'  # A cada 15 minutos (horário UTC)
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar script
        run: |
          python main.py
